In [1]:
import pandas as pd
import numpy as np
import joblib
import os

from IPython.display import display

print("Libraries imported.")

Libraries imported.

In [6]:
candidate_path = (
    "G:\\PMS_Optimization\\NOTEBOOKS\\outputs\\PBM_Candidate_Alternatives.csv"
)

candidates = pd.read_csv(
    candidate_path
)

print(
    "Candidate dataset:",
    candidates.shape
)

display(
    candidates.head()
)

Candidate dataset: (10969, 30)

,Ingredient,DF;Route,Trade_Name,Applicant,Strength,Appl_Type,Appl_No,Product_No,TE_Code,Approval_Date,...,RLD_Appl_No,RLD_Product_No,RLD_TE_Code,Patent_Count,Patent_Numbers,Patent_Expiry,Patent_Use_Codes,Exclusivity_Count,Exclusivity_Codes,Exclusivity_Dates
0,BUDESONIDE,"AEROSOL, FOAM;RECTAL",BUDESONIDE,PADAGIS ISRAEL,2MG/ACTUATION,A,215328,1,AB,"Apr 12, 2023",...,205613,1,AB,0.0,NaN,NaN,NaN,0.0,NaN,NaN
1,ALBUTEROL SULFATE,"AEROSOL, METERED;INHALATION",ALBUTEROL SULFATE,AMNEAL IRELAND LTD,EQ 0.09MG BASE/INH,A,211600,1,AB2,"Dec 1, 2025",...,21457,1,AB2,0.0,NaN,NaN,NaN,0.0,NaN,NaN
2,ALBUTEROL SULFATE,"AEROSOL, METERED;INHALATION",ALBUTEROL SULFATE,AMNEAL IRELAND LTD,EQ 0.09MG BASE/INH,A,211600,1,AB2,"Dec 1, 2025",...,20503,1,AB1,0.0,NaN,NaN,NaN,0.0,NaN,NaN
3,ALBUTEROL SULFATE,"AEROSOL, METERED;INHALATION",ALBUTEROL SULFATE,AMNEAL IRELAND LTD,EQ 0.09MG BASE/INH,A,211600,1,AB2,"Dec 1, 2025",...,20983,1,AB3,0.0,NaN,NaN,NaN,0.0,NaN,NaN
4,ALBUTEROL SULFATE,"AEROSOL, METERED;INHALATION",ALBUTEROL SULFATE,ARMSTRONG PHARMS,EQ 0.09MG BASE/INH,A,212447,1,AB2,"May 21, 2024",...,21457,1,AB2,0.0,NaN,NaN,NaN,0.0,NaN,NaN

In [7]:
model_path = (
    "G:\\PMS_Optimization\\models\\best_TE_model.pkl"
)

best_model = joblib.load(
    model_path
)

print(
    "Best TE model loaded successfully."
)

Best TE model loaded successfully.

In [8]:
features = [
    "Ingredient",
    "DF;Route",
    "Strength",
    "Appl_Type",
    "RLD",
    "RS",
    "Type",
    "Dosage_Form",
    "Route_Of_Administration",
    "Approved_Prior_To_1982"
]

X_candidates = candidates[
    features
].copy()

boolean_features = [
    "RLD",
    "RS",
    "Approved_Prior_To_1982"
]

for col in boolean_features:

    X_candidates[col] = (
        X_candidates[col]
        .fillna("")
        .astype(str)
        .str.strip()
        .str.lower()
        .map({
            "true": 1,
            "false": 0
        })
        .fillna(0)
    )

print(
    X_candidates.shape
)

(10969, 10)

In [9]:
predicted_te = best_model.predict(
    X_candidates
)

candidates["Predicted_TE_Code"] = (
    predicted_te
)

print(
    "TE predictions generated."
)

display(
    candidates[
        [
            "Trade_Name",
            "TE_Code",
            "Predicted_TE_Code"
        ]
    ].head(30)
)

TE predictions generated.

                                      Trade_Name TE_Code  Predicted_TE_Code
0                                     BUDESONIDE      AB                  1
1                              ALBUTEROL SULFATE     AB2                  7
2                              ALBUTEROL SULFATE     AB2                  7
3                              ALBUTEROL SULFATE     AB2                  7
4                              ALBUTEROL SULFATE     AB2                  7
5                              ALBUTEROL SULFATE     AB2                  7
6                              ALBUTEROL SULFATE     AB2                  7
7                              ALBUTEROL SULFATE     AB1                  7
8                              ALBUTEROL SULFATE     AB1                  7
9                              ALBUTEROL SULFATE     AB1                  7
10                             ALBUTEROL SULFATE     AB3                  7
11                             ALBUTEROL SULFATE     AB3                  7
12                             ALBUTEROL SULFATE     AB3                  7
13                             ALBUTEROL SULFATE     AB2                  7
14                             ALBUTEROL SULFATE     AB2                  7
15                             ALBUTEROL SULFATE     AB2                  7
16                             ALBUTEROL SULFATE     AB2                  7
17                             ALBUTEROL SULFATE     AB2                  7
18                             ALBUTEROL SULFATE     AB2                  7
19                             ALBUTEROL SULFATE     AB1                  7
20                             ALBUTEROL SULFATE     AB1                  7
21                             ALBUTEROL SULFATE     AB1                  7
22                           IPRATROPIUM BROMIDE      AB                  1
23                                        BREYNA      AB                  7
24  BUDESONIDE AND FORMOTEROL FUMARATE DIHYDRATE      AB                  7
25                                        BREYNA      AB                  1
26  BUDESONIDE AND FORMOTEROL FUMARATE DIHYDRATE      AB                  1
27                        FLUTICASONE PROPIONATE      AB                  1
28                      DULOXETINE HYDROCHLORIDE      AB                  1
29                      DULOXETINE HYDROCHLORIDE      AB                  1

In [10]:
print("Candidate columns:")
for i, col in enumerate(candidates.columns):
    print(i, ":", col)

Candidate columns:
0 : Ingredient
1 : DF;Route
2 : Trade_Name
3 : Applicant
4 : Strength
5 : Appl_Type
6 : Appl_No
7 : Product_No
8 : TE_Code
9 : Approval_Date
10 : RLD
11 : RS
12 : Type
13 : Applicant_Full_Name
14 : Dosage_Form
15 : Route_Of_Administration
16 : Approved_Prior_To_1982
17 : Approval_Date_ISO
18 : AB_Family
19 : RLD_Trade_Name
20 : RLD_Appl_No
21 : RLD_Product_No
22 : RLD_TE_Code
23 : Patent_Count
24 : Patent_Numbers
25 : Patent_Expiry
26 : Patent_Use_Codes
27 : Exclusivity_Count
28 : Exclusivity_Codes
29 : Exclusivity_Dates
30 : Predicted_TE_Code

In [11]:
display(candidates.head())

,Ingredient,DF;Route,Trade_Name,Applicant,Strength,Appl_Type,Appl_No,Product_No,TE_Code,Approval_Date,...,RLD_Product_No,RLD_TE_Code,Patent_Count,Patent_Numbers,Patent_Expiry,Patent_Use_Codes,Exclusivity_Count,Exclusivity_Codes,Exclusivity_Dates,Predicted_TE_Code
0,BUDESONIDE,"AEROSOL, FOAM;RECTAL",BUDESONIDE,PADAGIS ISRAEL,2MG/ACTUATION,A,215328,1,AB,"Apr 12, 2023",...,1,AB,0.0,NaN,NaN,NaN,0.0,NaN,NaN,1
1,ALBUTEROL SULFATE,"AEROSOL, METERED;INHALATION",ALBUTEROL SULFATE,AMNEAL IRELAND LTD,EQ 0.09MG BASE/INH,A,211600,1,AB2,"Dec 1, 2025",...,1,AB2,0.0,NaN,NaN,NaN,0.0,NaN,NaN,7
2,ALBUTEROL SULFATE,"AEROSOL, METERED;INHALATION",ALBUTEROL SULFATE,AMNEAL IRELAND LTD,EQ 0.09MG BASE/INH,A,211600,1,AB2,"Dec 1, 2025",...,1,AB1,0.0,NaN,NaN,NaN,0.0,NaN,NaN,7
3,ALBUTEROL SULFATE,"AEROSOL, METERED;INHALATION",ALBUTEROL SULFATE,AMNEAL IRELAND LTD,EQ 0.09MG BASE/INH,A,211600,1,AB2,"Dec 1, 2025",...,1,AB3,0.0,NaN,NaN,NaN,0.0,NaN,NaN,7
4,ALBUTEROL SULFATE,"AEROSOL, METERED;INHALATION",ALBUTEROL SULFATE,ARMSTRONG PHARMS,EQ 0.09MG BASE/INH,A,212447,1,AB2,"May 21, 2024",...,1,AB2,0.0,NaN,NaN,NaN,0.0,NaN,NaN,7

In [12]:
score_related_columns = [
    col for col in candidates.columns
    if any(word in col.lower()
           for word in ["patent", "exclusivity", "rs", "te"])
]

print("Scoring-related columns:")
print(score_related_columns)

Scoring-related columns:
['DF;Route', 'TE_Code', 'Approval_Date', 'RS', 'Route_Of_Administration', 'Approval_Date_ISO', 'RLD_TE_Code', 'Patent_Count', 'Patent_Numbers', 'Patent_Expiry', 'Patent_Use_Codes', 'Exclusivity_Count', 'Exclusivity_Codes', 'Exclusivity_Dates', 'Predicted_TE_Code']

In [13]:
# ============================================================
# TE SCORE
# ============================================================

ab_family_codes = candidates["Predicted_TE_Code"].astype(str).str.upper().str.strip()

candidates["TE_Score"] = np.where(
    ab_family_codes.str.startswith("AB"),
    1.0,
    0.0
)

print("TE Score distribution:")
print(candidates["TE_Score"].value_counts())

display(
    candidates[
        [
            "Trade_Name",
            "TE_Code",
            "Predicted_TE_Code",
            "TE_Score"
        ]
    ].head(20)
)

TE Score distribution:
TE_Score
0.0    10969
Name: count, dtype: int64

           Trade_Name TE_Code  Predicted_TE_Code  TE_Score
0          BUDESONIDE      AB                  1       0.0
1   ALBUTEROL SULFATE     AB2                  7       0.0
2   ALBUTEROL SULFATE     AB2                  7       0.0
3   ALBUTEROL SULFATE     AB2                  7       0.0
4   ALBUTEROL SULFATE     AB2                  7       0.0
5   ALBUTEROL SULFATE     AB2                  7       0.0
6   ALBUTEROL SULFATE     AB2                  7       0.0
7   ALBUTEROL SULFATE     AB1                  7       0.0
8   ALBUTEROL SULFATE     AB1                  7       0.0
9   ALBUTEROL SULFATE     AB1                  7       0.0
10  ALBUTEROL SULFATE     AB3                  7       0.0
11  ALBUTEROL SULFATE     AB3                  7       0.0
12  ALBUTEROL SULFATE     AB3                  7       0.0
13  ALBUTEROL SULFATE     AB2                  7       0.0
14  ALBUTEROL SULFATE     AB2                  7       0.0
15  ALBUTEROL SULFATE     AB2                  7       0.0
16  ALBUTEROL SULFATE     AB2                  7       0.0
17  ALBUTEROL SULFATE     AB2                  7       0.0
18  ALBUTEROL SULFATE     AB2                  7       0.0
19  ALBUTEROL SULFATE     AB1                  7       0.0

In [14]:
# ============================================================
# PATENT SCORE
# ============================================================

candidates["Patent_Count"] = pd.to_numeric(
    candidates["Patent_Count"],
    errors="coerce"
).fillna(0)

max_patents = candidates["Patent_Count"].max()

if max_patents > 0:
    candidates["Patent_Score"] = (
        1 - candidates["Patent_Count"] / max_patents
    )
else:
    candidates["Patent_Score"] = 1.0

print("Patent Score created.")

display(
    candidates[
        [
            "Trade_Name",
            "Patent_Count",
            "Patent_Score"
        ]
    ].head(20)
)

Patent Score created.

           Trade_Name  Patent_Count  Patent_Score
0          BUDESONIDE           0.0           1.0
1   ALBUTEROL SULFATE           0.0           1.0
2   ALBUTEROL SULFATE           0.0           1.0
3   ALBUTEROL SULFATE           0.0           1.0
4   ALBUTEROL SULFATE           0.0           1.0
5   ALBUTEROL SULFATE           0.0           1.0
6   ALBUTEROL SULFATE           0.0           1.0
7   ALBUTEROL SULFATE           0.0           1.0
8   ALBUTEROL SULFATE           0.0           1.0
9   ALBUTEROL SULFATE           0.0           1.0
10  ALBUTEROL SULFATE           0.0           1.0
11  ALBUTEROL SULFATE           0.0           1.0
12  ALBUTEROL SULFATE           0.0           1.0
13  ALBUTEROL SULFATE           0.0           1.0
14  ALBUTEROL SULFATE           0.0           1.0
15  ALBUTEROL SULFATE           0.0           1.0
16  ALBUTEROL SULFATE           0.0           1.0
17  ALBUTEROL SULFATE           0.0           1.0
18  ALBUTEROL SULFATE           0.0           1.0
19  ALBUTEROL SULFATE           0.0           1.0

In [15]:
# ============================================================
# EXCLUSIVITY SCORE
# ============================================================

candidates["Exclusivity_Count"] = pd.to_numeric(
    candidates["Exclusivity_Count"],
    errors="coerce"
).fillna(0)

max_exclusivity = candidates["Exclusivity_Count"].max()

if max_exclusivity > 0:
    candidates["Exclusivity_Score"] = (
        1 - candidates["Exclusivity_Count"] / max_exclusivity
    )
else:
    candidates["Exclusivity_Score"] = 1.0

print("Exclusivity Score created.")

display(
    candidates[
        [
            "Trade_Name",
            "Exclusivity_Count",
            "Exclusivity_Score"
        ]
    ].head(20)
)

Exclusivity Score created.

           Trade_Name  Exclusivity_Count  Exclusivity_Score
0          BUDESONIDE                0.0                1.0
1   ALBUTEROL SULFATE                0.0                1.0
2   ALBUTEROL SULFATE                0.0                1.0
3   ALBUTEROL SULFATE                0.0                1.0
4   ALBUTEROL SULFATE                0.0                1.0
5   ALBUTEROL SULFATE                0.0                1.0
6   ALBUTEROL SULFATE                0.0                1.0
7   ALBUTEROL SULFATE                0.0                1.0
8   ALBUTEROL SULFATE                0.0                1.0
9   ALBUTEROL SULFATE                0.0                1.0
10  ALBUTEROL SULFATE                1.0                0.0
11  ALBUTEROL SULFATE                1.0                0.0
12  ALBUTEROL SULFATE                1.0                0.0
13  ALBUTEROL SULFATE                0.0                1.0
14  ALBUTEROL SULFATE                0.0                1.0
15  ALBUTEROL SULFATE                0.0                1.0
16  ALBUTEROL SULFATE                0.0                1.0
17  ALBUTEROL SULFATE                0.0                1.0
18  ALBUTEROL SULFATE                0.0                1.0
19  ALBUTEROL SULFATE                0.0                1.0

In [16]:
# ============================================================
# RS SCORE
# ============================================================

candidates["RS_Score"] = (
    candidates["RS"]
    .fillna(False)
    .astype(str)
    .str.strip()
    .str.lower()
    .map({
        "true": 1.0,
        "false": 0.0,
        "1": 1.0,
        "0": 0.0
    })
    .fillna(0.0)
)

print("RS Score created.")

display(
    candidates[
        [
            "Trade_Name",
            "RS",
            "RS_Score"
        ]
    ].head(20)
)

RS Score created.

           Trade_Name     RS  RS_Score
0          BUDESONIDE   True       1.0
1   ALBUTEROL SULFATE  False       0.0
2   ALBUTEROL SULFATE  False       0.0
3   ALBUTEROL SULFATE  False       0.0
4   ALBUTEROL SULFATE  False       0.0
5   ALBUTEROL SULFATE  False       0.0
6   ALBUTEROL SULFATE  False       0.0
7   ALBUTEROL SULFATE  False       0.0
8   ALBUTEROL SULFATE  False       0.0
9   ALBUTEROL SULFATE  False       0.0
10  ALBUTEROL SULFATE  False       0.0
11  ALBUTEROL SULFATE  False       0.0
12  ALBUTEROL SULFATE  False       0.0
13  ALBUTEROL SULFATE  False       0.0
14  ALBUTEROL SULFATE  False       0.0
15  ALBUTEROL SULFATE  False       0.0
16  ALBUTEROL SULFATE  False       0.0
17  ALBUTEROL SULFATE  False       0.0
18  ALBUTEROL SULFATE  False       0.0
19  ALBUTEROL SULFATE  False       0.0

In [17]:
# ============================================================
# FINAL PBM SCORE
# ============================================================

TE_WEIGHT = 0.40
PATENT_WEIGHT = 0.25
EXCLUSIVITY_WEIGHT = 0.20
RS_WEIGHT = 0.15

candidates["Final_Score"] = (
    TE_WEIGHT * candidates["TE_Score"]
    + PATENT_WEIGHT * candidates["Patent_Score"]
    + EXCLUSIVITY_WEIGHT * candidates["Exclusivity_Score"]
    + RS_WEIGHT * candidates["RS_Score"]
)

print("Final PBM score calculated.")

display(
    candidates[
        [
            "Trade_Name",
            "Predicted_TE_Code",
            "TE_Score",
            "Patent_Score",
            "Exclusivity_Score",
            "RS_Score",
            "Final_Score"
        ]
    ].head(20)
)

Final PBM score calculated.

,Trade_Name,Predicted_TE_Code,TE_Score,Patent_Score,Exclusivity_Score,RS_Score,Final_Score
0,BUDESONIDE,1,0.0,1.0,1.0,1.0,0.60
1,ALBUTEROL SULFATE,7,0.0,1.0,1.0,0.0,0.45
2,ALBUTEROL SULFATE,7,0.0,1.0,1.0,0.0,0.45
3,ALBUTEROL SULFATE,7,0.0,1.0,1.0,0.0,0.45
4,ALBUTEROL SULFATE,7,0.0,1.0,1.0,0.0,0.45
5,ALBUTEROL SULFATE,7,0.0,1.0,1.0,0.0,0.45
6,ALBUTEROL SULFATE,7,0.0,1.0,1.0,0.0,0.45
7,ALBUTEROL SULFATE,7,0.0,1.0,1.0,0.0,0.45
8,ALBUTEROL SULFATE,7,0.0,1.0,1.0,0.0,0.45
9,ALBUTEROL SULFATE,7,0.0,1.0,1.0,0.0,0.45
10,ALBUTEROL SULFATE,7,0.0,1.0,0.0,0.0,0.25
11,ALBUTEROL SULFATE,7,0.0,1.0,0.0,0.0,0.25
12,ALBUTEROL SULFATE,7,0.0,1.0,0.0,0.0,0.25
13,ALBUTEROL SULFATE,7,0.0,1.0,1.0,0.0,0.45
14,ALBUTEROL SULFATE,7,0.0,1.0,1.0,0.0,0.45
15,ALBUTEROL SULFATE,7,0.0,1.0,1.0,0.0,0.45
16,ALBUTEROL SULFATE,7,0.0,1.0,1.0,0.0,0.45
17,ALBUTEROL SULFATE,7,0.0,1.0,1.0,0.0,0.45
18,ALBUTEROL SULFATE,7,0.0,1.0,1.0,0.0,0.45
19,ALBUTEROL SULFATE,7,0.0,1.0,1.0,0.0,0.45

In [18]:
# ============================================================
# FIX PREDICTED TE CODE
# Convert numeric model prediction back to actual TE code
# ============================================================

te_label_map = {
    0: "AA",
    1: "AB",
    2: "AB1",
    3: "AB1,AB2",
    4: "AB1,AB2,AB3",
    5: "AB1,AB2,AB3,AB4",
    6: "AB1,AB3",
    7: "AB2",
    8: "AB3",
    9: "AB4",
    10: "AN",
    11: "AO",
    12: "AP",
    13: "AP1",
    14: "AP2",
    15: "AP3",
    16: "AT",
    17: "AT1",
    18: "AT2",
    19: "AT3",
    20: "BD",
    21: "BP",
    22: "BX"
}

candidates["Predicted_TE_Code"] = (
    pd.to_numeric(
        candidates["Predicted_TE_Code"],
        errors="coerce"
    )
    .map(te_label_map)
)

print("Converted predicted TE codes:")

display(
    candidates[
        [
            "Trade_Name",
            "TE_Code",
            "Predicted_TE_Code"
        ]
    ].head(30)
)

Converted predicted TE codes:

                                      Trade_Name TE_Code Predicted_TE_Code
0                                     BUDESONIDE      AB                AB
1                              ALBUTEROL SULFATE     AB2               AB2
2                              ALBUTEROL SULFATE     AB2               AB2
3                              ALBUTEROL SULFATE     AB2               AB2
4                              ALBUTEROL SULFATE     AB2               AB2
5                              ALBUTEROL SULFATE     AB2               AB2
6                              ALBUTEROL SULFATE     AB2               AB2
7                              ALBUTEROL SULFATE     AB1               AB2
8                              ALBUTEROL SULFATE     AB1               AB2
9                              ALBUTEROL SULFATE     AB1               AB2
10                             ALBUTEROL SULFATE     AB3               AB2
11                             ALBUTEROL SULFATE     AB3               AB2
12                             ALBUTEROL SULFATE     AB3               AB2
13                             ALBUTEROL SULFATE     AB2               AB2
14                             ALBUTEROL SULFATE     AB2               AB2
15                             ALBUTEROL SULFATE     AB2               AB2
16                             ALBUTEROL SULFATE     AB2               AB2
17                             ALBUTEROL SULFATE     AB2               AB2
18                             ALBUTEROL SULFATE     AB2               AB2
19                             ALBUTEROL SULFATE     AB1               AB2
20                             ALBUTEROL SULFATE     AB1               AB2
21                             ALBUTEROL SULFATE     AB1               AB2
22                           IPRATROPIUM BROMIDE      AB                AB
23                                        BREYNA      AB               AB2
24  BUDESONIDE AND FORMOTEROL FUMARATE DIHYDRATE      AB               AB2
25                                        BREYNA      AB                AB
26  BUDESONIDE AND FORMOTEROL FUMARATE DIHYDRATE      AB                AB
27                        FLUTICASONE PROPIONATE      AB                AB
28                      DULOXETINE HYDROCHLORIDE      AB                AB
29                      DULOXETINE HYDROCHLORIDE      AB                AB

In [31]:
# ============================================================
# RECALCULATE TE SCORE
# ============================================================

def calculate_te_score(te_code):

    if pd.isna(te_code):
        return 0.0

    te_code = str(te_code).strip().upper()

    # Best equivalence
    if te_code == "AB":
        return 1.0

    # Other acceptable AB categories
    elif te_code.startswith("AB"):
        return 0.8

    # Other TE categories
    elif te_code in ["AA", "AN", "AO", "AP", "AP1", "AP2", "AP3"]:
        return 0.5

    else:
        return 0.0


candidates["TE_Score"] = (
    candidates["Predicted_TE_Code"]
    .apply(calculate_te_score)
)

print("TE Score recalculated successfully.")

display(
    candidates[
        [
            "Trade_Name",
            "TE_Code",
            "Predicted_TE_Code",
            "TE_Score"
        ]
    ].head(30)
)

TE Score recalculated successfully.

,Trade_Name,TE_Code,Predicted_TE_Code,TE_Score
0,BUDESONIDE,AB,AB,1.0
1,ALBUTEROL SULFATE,AB2,AB2,0.8
2,ALBUTEROL SULFATE,AB2,AB2,0.8
3,ALBUTEROL SULFATE,AB2,AB2,0.8
4,ALBUTEROL SULFATE,AB2,AB2,0.8
5,ALBUTEROL SULFATE,AB2,AB2,0.8
6,ALBUTEROL SULFATE,AB2,AB2,0.8
7,ALBUTEROL SULFATE,AB1,AB2,0.8
8,ALBUTEROL SULFATE,AB1,AB2,0.8
9,ALBUTEROL SULFATE,AB1,AB2,0.8
10,ALBUTEROL SULFATE,AB3,AB2,0.8
11,ALBUTEROL SULFATE,AB3,AB2,0.8
12,ALBUTEROL SULFATE,AB3,AB2,0.8
13,ALBUTEROL SULFATE,AB2,AB2,0.8
14,ALBUTEROL SULFATE,AB2,AB2,0.8
15,ALBUTEROL SULFATE,AB2,AB2,0.8
16,ALBUTEROL SULFATE,AB2,AB2,0.8
17,ALBUTEROL SULFATE,AB2,AB2,0.8
18,ALBUTEROL SULFATE,AB2,AB2,0.8
19,ALBUTEROL SULFATE,AB1,AB2,0.8
20,ALBUTEROL SULFATE,AB1,AB2,0.8
21,ALBUTEROL SULFATE,AB1,AB2,0.8
22,IPRATROPIUM BROMIDE,AB,AB,1.0
23,BREYNA,AB,AB2,0.8
24,BUDESONIDE AND FORMOTEROL FUMARATE DIHYDRATE,AB,AB2,0.8
25,BREYNA,AB,AB,1.0
26,BUDESONIDE AND FORMOTEROL FUMARATE DIHYDRATE,AB,AB,1.0
27,FLUTICASONE PROPIONATE,AB,AB,1.0
28,DULOXETINE HYDROCHLORIDE,AB,AB,1.0
29,DULOXETINE HYDROCHLORIDE,AB,AB,1.0

In [32]:
# ============================================================
# RECALCULATE FINAL PBM SCORE
# ============================================================

candidates["Final_Score"] = (
    0.40 * candidates["TE_Score"]
    + 0.25 * candidates["Patent_Score"]
    + 0.20 * candidates["Exclusivity_Score"]
    + 0.15 * candidates["RS_Score"]
)

print("Final PBM Score recalculated.")

display(
    candidates[
        [
            "Trade_Name",
            "Predicted_TE_Code",
            "TE_Score",
            "Patent_Score",
            "Exclusivity_Score",
            "RS_Score",
            "Final_Score"
        ]
    ].head(20)
)

Final PBM Score recalculated.

,Trade_Name,Predicted_TE_Code,TE_Score,Patent_Score,Exclusivity_Score,RS_Score,Final_Score
0,BUDESONIDE,AB,1.0,1.0,1.0,1.0,1.00
1,ALBUTEROL SULFATE,AB2,0.8,1.0,1.0,0.0,0.77
2,ALBUTEROL SULFATE,AB2,0.8,1.0,1.0,0.0,0.77
3,ALBUTEROL SULFATE,AB2,0.8,1.0,1.0,0.0,0.77
4,ALBUTEROL SULFATE,AB2,0.8,1.0,1.0,0.0,0.77
5,ALBUTEROL SULFATE,AB2,0.8,1.0,1.0,0.0,0.77
6,ALBUTEROL SULFATE,AB2,0.8,1.0,1.0,0.0,0.77
7,ALBUTEROL SULFATE,AB2,0.8,1.0,1.0,0.0,0.77
8,ALBUTEROL SULFATE,AB2,0.8,1.0,1.0,0.0,0.77
9,ALBUTEROL SULFATE,AB2,0.8,1.0,1.0,0.0,0.77
10,ALBUTEROL SULFATE,AB2,0.8,1.0,0.0,0.0,0.57
11,ALBUTEROL SULFATE,AB2,0.8,1.0,0.0,0.0,0.57
12,ALBUTEROL SULFATE,AB2,0.8,1.0,0.0,0.0,0.57
13,ALBUTEROL SULFATE,AB2,0.8,1.0,1.0,0.0,0.77
14,ALBUTEROL SULFATE,AB2,0.8,1.0,1.0,0.0,0.77
15,ALBUTEROL SULFATE,AB2,0.8,1.0,1.0,0.0,0.77
16,ALBUTEROL SULFATE,AB2,0.8,1.0,1.0,0.0,0.77
17,ALBUTEROL SULFATE,AB2,0.8,1.0,1.0,0.0,0.77
18,ALBUTEROL SULFATE,AB2,0.8,1.0,1.0,0.0,0.77
19,ALBUTEROL SULFATE,AB2,0.8,1.0,1.0,0.0,0.77

In [33]:
# ============================================================
# FINAL CANDIDATE RANKING
# ============================================================

ranked_candidates = (
    candidates
    .sort_values(
        by="Final_Score",
        ascending=False
    )
    .reset_index(drop=True)
)

ranked_candidates["Rank"] = (
    ranked_candidates.index + 1
)

print("Candidates ranked successfully.")

display(
    ranked_candidates[
        [
            "Rank",
            "Trade_Name",
            "Ingredient",
            "Strength",
            "Dosage_Form",
            "Route_Of_Administration",
            "Predicted_TE_Code",
            "TE_Score",
            "Patent_Score",
            "Exclusivity_Score",
            "RS_Score",
            "Final_Score"
        ]
    ].head(20)
)

Candidates ranked successfully.

,Rank,Trade_Name,Ingredient,Strength,Dosage_Form,Route_Of_Administration,Predicted_TE_Code,TE_Score,Patent_Score,Exclusivity_Score,RS_Score,Final_Score
0,1,BUDESONIDE,BUDESONIDE,2MG/ACTUATION,"AEROSOL, FOAM",RECTAL,AB,1.0,1.0,1.0,1.0,1.0
1,2,DUTASTERIDE AND TAMSULOSIN HYDROCHLORIDE,DUTASTERIDE; TAMSULOSIN HYDROCHLORIDE,0.5MG;0.4MG,CAPSULE,ORAL,AB,1.0,1.0,1.0,1.0,1.0
2,3,LISINOPRIL AND HYDROCHLOROTHIAZIDE,HYDROCHLOROTHIAZIDE; LISINOPRIL,25MG;20MG,TABLET,ORAL,AB,1.0,1.0,1.0,1.0,1.0
3,4,DOXYCYCLINE HYCLATE,DOXYCYCLINE HYCLATE,EQ 200MG BASE,"TABLET, DELAYED RELEASE",ORAL,AB,1.0,1.0,1.0,1.0,1.0
4,5,PHENOXYBENZAMINE HYDROCHLORIDE,PHENOXYBENZAMINE HYDROCHLORIDE,10MG,CAPSULE,ORAL,AB,1.0,1.0,1.0,1.0,1.0
5,6,LINEZOLID,LINEZOLID,600MG,TABLET,ORAL,AB,1.0,1.0,1.0,1.0,1.0
6,7,LEVOCETIRIZINE DIHYDROCHLORIDE,LEVOCETIRIZINE DIHYDROCHLORIDE,5MG,TABLET,ORAL,AB,1.0,1.0,1.0,1.0,1.0
7,8,DOXERCALCIFEROL,DOXERCALCIFEROL,2.5MCG,CAPSULE,ORAL,AB,1.0,1.0,1.0,1.0,1.0
8,9,BROMOCRIPTINE MESYLATE,BROMOCRIPTINE MESYLATE,EQ 2.5MG BASE,TABLET,ORAL,AB,1.0,1.0,1.0,1.0,1.0
9,10,SODIUM PHENYLBUTYRATE,SODIUM PHENYLBUTYRATE,500MG,TABLET,ORAL,AB,1.0,1.0,1.0,1.0,1.0
10,11,DOXYCYCLINE,DOXYCYCLINE,EQ 100MG BASE,CAPSULE,ORAL,AB,1.0,1.0,1.0,1.0,1.0
11,12,DOXYCYCLINE,DOXYCYCLINE,EQ 150MG BASE,CAPSULE,ORAL,AB,1.0,1.0,1.0,1.0,1.0
12,13,MINOCYCLINE HYDROCHLORIDE,MINOCYCLINE HYDROCHLORIDE,EQ 100MG BASE,CAPSULE,ORAL,AB,1.0,1.0,1.0,1.0,1.0
13,14,CALCITRIOL,CALCITRIOL,0.5MCG,CAPSULE,ORAL,AB,1.0,1.0,1.0,1.0,1.0
14,15,ETODOLAC,ETODOLAC,300MG,CAPSULE,ORAL,AB,1.0,1.0,1.0,1.0,1.0
15,16,ETOPOSIDE,ETOPOSIDE,50MG,CAPSULE,ORAL,AB,1.0,1.0,1.0,1.0,1.0
16,17,CARBIDOPA AND LEVODOPA,CARBIDOPA; LEVODOPA,25MG;250MG,TABLET,ORAL,AB,1.0,1.0,1.0,1.0,1.0
17,18,LAMOTRIGINE,LAMOTRIGINE,25MG,TABLET,ORAL,AB,1.0,1.0,1.0,1.0,1.0
18,19,TAMSULOSIN HYDROCHLORIDE,TAMSULOSIN HYDROCHLORIDE,0.4MG,CAPSULE,ORAL,AB,1.0,1.0,1.0,1.0,1.0
19,20,NAPROXEN,NAPROXEN,25MG/ML,SUSPENSION,ORAL,AB,1.0,1.0,1.0,1.0,1.0

In [35]:
# ============================================================
# BEST PBM ALTERNATIVE
# ============================================================

best_candidate = ranked_candidates.iloc[0]

print("=" * 60)
print("BEST PBM ALTERNATIVE")
print("=" * 60)

print("Trade Name       :", best_candidate["Trade_Name"])
print("Ingredient       :", best_candidate["Ingredient"])
print("Strength         :", best_candidate["Strength"])
print("Dosage Form      :", best_candidate["Dosage_Form"])
print("Route            :", best_candidate["Route_Of_Administration"])
print("Predicted TE     :", best_candidate["Predicted_TE_Code"])
print("TE Score         :", best_candidate["TE_Score"])
print("Patent Score     :", best_candidate["Patent_Score"])
print("Exclusivity Score:", best_candidate["Exclusivity_Score"])
print("RS Score         :", best_candidate["RS_Score"])
print("Final Score      :", best_candidate["Final_Score"])
print("Rank             :", best_candidate["Rank"])

print("=" * 60)

============================================================
BEST PBM ALTERNATIVE
============================================================
Trade Name       : BUDESONIDE
Ingredient       : BUDESONIDE
Strength         : 2MG/ACTUATION
Dosage Form      : AEROSOL, FOAM
Route            : RECTAL
Predicted TE     : AB
TE Score         : 1.0
Patent Score     : 1.0
Exclusivity Score: 1.0
RS Score         : 1.0
Final Score      : 1.0
Rank             : 1
============================================================

In [36]:
# ============================================================
# TOP 10 PBM RECOMMENDATIONS
# ============================================================

top_10 = ranked_candidates.head(10)

display(
    top_10[
        [
            "Rank",
            "Trade_Name",
            "Ingredient",
            "Strength",
            "Dosage_Form",
            "Route_Of_Administration",
            "Predicted_TE_Code",
            "Final_Score"
        ]
    ]
)

,Rank,Trade_Name,Ingredient,Strength,Dosage_Form,Route_Of_Administration,Predicted_TE_Code,Final_Score
0,1,BUDESONIDE,BUDESONIDE,2MG/ACTUATION,"AEROSOL, FOAM",RECTAL,AB,1.0
1,2,DUTASTERIDE AND TAMSULOSIN HYDROCHLORIDE,DUTASTERIDE; TAMSULOSIN HYDROCHLORIDE,0.5MG;0.4MG,CAPSULE,ORAL,AB,1.0
2,3,LISINOPRIL AND HYDROCHLOROTHIAZIDE,HYDROCHLOROTHIAZIDE; LISINOPRIL,25MG;20MG,TABLET,ORAL,AB,1.0
3,4,DOXYCYCLINE HYCLATE,DOXYCYCLINE HYCLATE,EQ 200MG BASE,"TABLET, DELAYED RELEASE",ORAL,AB,1.0
4,5,PHENOXYBENZAMINE HYDROCHLORIDE,PHENOXYBENZAMINE HYDROCHLORIDE,10MG,CAPSULE,ORAL,AB,1.0
5,6,LINEZOLID,LINEZOLID,600MG,TABLET,ORAL,AB,1.0
6,7,LEVOCETIRIZINE DIHYDROCHLORIDE,LEVOCETIRIZINE DIHYDROCHLORIDE,5MG,TABLET,ORAL,AB,1.0
7,8,DOXERCALCIFEROL,DOXERCALCIFEROL,2.5MCG,CAPSULE,ORAL,AB,1.0
8,9,BROMOCRIPTINE MESYLATE,BROMOCRIPTINE MESYLATE,EQ 2.5MG BASE,TABLET,ORAL,AB,1.0
9,10,SODIUM PHENYLBUTYRATE,SODIUM PHENYLBUTYRATE,500MG,TABLET,ORAL,AB,1.0

In [37]:
# ============================================================
# SAVE OPTIMIZED RESULTS
# ============================================================

output_dir = r"G:\PMS_Optimization\NOTEBOOKS\outputs"

os.makedirs(output_dir, exist_ok=True)

output_path = os.path.join(
    output_dir,
    "PBM_Optimized_Candidates.csv"
)

ranked_candidates.to_csv(
    output_path,
    index=False
)

print("PBM optimized results saved successfully.")
print(output_path)

PBM optimized results saved successfully.
G:\PMS_Optimization\NOTEBOOKS\outputs\PBM_Optimized_Candidates.csv

In [39]:
# ============================================================
# FINAL PBM RESULT CHECK
# ============================================================

print("Number of candidates:", len(ranked_candidates))

print("\nFinal Score range:")
print("Minimum:", ranked_candidates["Final_Score"].min())
print("Maximum:", ranked_candidates["Final_Score"].max())

print("\nTop 10 PBM Candidates:")

display(
    ranked_candidates[
        [
            "Rank",
            "Trade_Name",
            "Ingredient",
            "Predicted_TE_Code",
            "TE_Score",
            "Patent_Score",
            "Exclusivity_Score",
            "RS_Score",
            "Final_Score"
        ]
    ].head(10)
)

Number of candidates: 10969

Final Score range:
Minimum: 0.45
Maximum: 1.0

Top 10 PBM Candidates:

,Rank,Trade_Name,Ingredient,Predicted_TE_Code,TE_Score,Patent_Score,Exclusivity_Score,RS_Score,Final_Score
0,1,BUDESONIDE,BUDESONIDE,AB,1.0,1.0,1.0,1.0,1.0
1,2,DUTASTERIDE AND TAMSULOSIN HYDROCHLORIDE,DUTASTERIDE; TAMSULOSIN HYDROCHLORIDE,AB,1.0,1.0,1.0,1.0,1.0
2,3,LISINOPRIL AND HYDROCHLOROTHIAZIDE,HYDROCHLOROTHIAZIDE; LISINOPRIL,AB,1.0,1.0,1.0,1.0,1.0
3,4,DOXYCYCLINE HYCLATE,DOXYCYCLINE HYCLATE,AB,1.0,1.0,1.0,1.0,1.0
4,5,PHENOXYBENZAMINE HYDROCHLORIDE,PHENOXYBENZAMINE HYDROCHLORIDE,AB,1.0,1.0,1.0,1.0,1.0
5,6,LINEZOLID,LINEZOLID,AB,1.0,1.0,1.0,1.0,1.0
6,7,LEVOCETIRIZINE DIHYDROCHLORIDE,LEVOCETIRIZINE DIHYDROCHLORIDE,AB,1.0,1.0,1.0,1.0,1.0
7,8,DOXERCALCIFEROL,DOXERCALCIFEROL,AB,1.0,1.0,1.0,1.0,1.0
8,9,BROMOCRIPTINE MESYLATE,BROMOCRIPTINE MESYLATE,AB,1.0,1.0,1.0,1.0,1.0
9,10,SODIUM PHENYLBUTYRATE,SODIUM PHENYLBUTYRATE,AB,1.0,1.0,1.0,1.0,1.0

In [40]:
# ============================================================
# CHECK RANKING
# ============================================================

is_sorted = ranked_candidates["Final_Score"].is_monotonic_decreasing

print("Scores sorted correctly:", is_sorted)

print("\nRank values:")
print(
    ranked_candidates["Rank"].head(10).tolist()
)

Scores sorted correctly: True

Rank values:
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [41]:
# ============================================================
# FINAL DATA QUALITY CHECK
# ============================================================

score_columns = [
    "TE_Score",
    "Patent_Score",
    "Exclusivity_Score",
    "RS_Score",
    "Final_Score"
]

print("Missing values in scoring columns:")

display(
    ranked_candidates[score_columns]
    .isnull()
    .sum()
)

Missing values in scoring columns:

TE_Score             0
Patent_Score         0
Exclusivity_Score    0
RS_Score             0
Final_Score          0
dtype: int64

In [42]:
# ============================================================
# FINAL RECOMMENDATION
# ============================================================

best = ranked_candidates.iloc[0]

print("\n" + "=" * 70)
print("FINAL PBM RECOMMENDATION")
print("=" * 70)

print("Rank              :", best["Rank"])
print("Trade Name        :", best["Trade_Name"])
print("Ingredient        :", best["Ingredient"])
print("Strength          :", best["Strength"])
print("Dosage Form       :", best["Dosage_Form"])
print("Route             :", best["Route_Of_Administration"])
print("Predicted TE Code :", best["Predicted_TE_Code"])
print("TE Score          :", best["TE_Score"])
print("Patent Score      :", best["Patent_Score"])
print("Exclusivity Score :", best["Exclusivity_Score"])
print("RS Score          :", best["RS_Score"])
print("Final PBM Score   :", best["Final_Score"])

print("=" * 70)

======================================================================
FINAL PBM RECOMMENDATION
======================================================================
Rank              : 1
Trade Name        : BUDESONIDE
Ingredient        : BUDESONIDE
Strength          : 2MG/ACTUATION
Dosage Form       : AEROSOL, FOAM
Route             : RECTAL
Predicted TE Code : AB
TE Score          : 1.0
Patent Score      : 1.0
Exclusivity Score : 1.0
RS Score          : 1.0
Final PBM Score   : 1.0
======================================================================

In [43]:
# ============================================================
# FINAL SCORE DISTRIBUTION
# ============================================================

score_distribution = (
    ranked_candidates["Final_Score"]
    .value_counts()
    .sort_index(ascending=False)
)

print("Final Score Distribution:")
display(score_distribution)

Final Score Distribution:

Final_Score
1.000000     108
0.920000      28
0.850000    8477
0.800000       7
0.770000    1684
0.650000     257
0.603333      29
0.600000       5
0.570000       3
0.520000       1
0.450000     370
Name: count, dtype: int64

In [44]:
# ============================================================
# NUMBER OF TOP-SCORE CANDIDATES
# ============================================================

print(
    "Candidates with Final Score = 1.0:",
    (ranked_candidates["Final_Score"] == 1.0).sum()
)

print(
    "Candidates with Final Score >= 0.8:",
    (ranked_candidates["Final_Score"] >= 0.8).sum()
)

Candidates with Final Score = 1.0: 108
Candidates with Final Score >= 0.8: 8620