In [5]:
import pandas as pd
import numpy as np
import os


utilization_path = r"..\trend_prediction_model\team_handoff\trend_prediction_handoff.csv"


te_path = r"..\te_equivalence\NOTEBOOKS\outputs\PBM_Optimized_Candidates.csv"

utilization = pd.read_csv(utilization_path)
te_data = pd.read_csv(te_path)

print("Utilization:", utilization.shape)
print("TE:", te_data.shape)

display(utilization.head())
display(te_data.head())

Utilization: (1451, 8)
TE: (10969, 37)

,Gnrc_Name,Brnd_Name,Predicted_2024_Claims,Predicted_2024_Benes,Predicted_2024_Cost,Cost_Growth_Pct,Growth_Flag,Note
0,Semaglutide,Ozempic,11006950,2478846,1.114179e+10,15.2,HIGH_GROWTH,Top-10% historical cost — verify growth % agai...
1,Empagliflozin,Jardiance,9867339,2478205,9.149159e+09,13.9,HIGH_GROWTH,Top-10% historical cost — verify growth % agai...
2,Apixaban,Eliquis,22611767,5357915,6.873779e+09,-60.5,HIGH_GROWTH,Top-10% historical cost — verify growth % agai...
3,Dulaglutide,Trulicity,5547127,1212388,5.417276e+09,-18.7,HIGH_GROWTH,Top-10% historical cost — verify growth % agai...
4,Fluticasone/Umeclidin/Vilanter,Trelegy Ellipta,5625746,1368179,5.243668e+09,30.7,HIGH_GROWTH,Top-10% historical cost — verify growth % agai...

,Ingredient,DF;Route,Trade_Name,Applicant,Strength,Appl_Type,Appl_No,Product_No,TE_Code,Approval_Date,...,Exclusivity_Count,Exclusivity_Codes,Exclusivity_Dates,Predicted_TE_Code,TE_Score,Patent_Score,Exclusivity_Score,RS_Score,Final_Score,Rank
0,BUDESONIDE,"AEROSOL, FOAM;RECTAL",BUDESONIDE,PADAGIS ISRAEL,2MG/ACTUATION,A,215328,1,AB,"Apr 12, 2023",...,0.0,NaN,NaN,AB,1.0,1.0,1.0,1.0,1.0,1
1,DUTASTERIDE; TAMSULOSIN HYDROCHLORIDE,CAPSULE;ORAL,DUTASTERIDE AND TAMSULOSIN HYDROCHLORIDE,ZYDUS PHARMS,0.5MG;0.4MG,A,207769,1,AB,"May 24, 2018",...,0.0,NaN,NaN,AB,1.0,1.0,1.0,1.0,1.0,2
2,HYDROCHLOROTHIAZIDE; LISINOPRIL,TABLET;ORAL,LISINOPRIL AND HYDROCHLOROTHIAZIDE,INVAGEN PHARMS,25MG;20MG,A,204058,3,AB,"May 23, 2017",...,0.0,NaN,NaN,AB,1.0,1.0,1.0,1.0,1.0,3
3,DOXYCYCLINE HYCLATE,"TABLET, DELAYED RELEASE;ORAL",DOXYCYCLINE HYCLATE,HERITAGE,EQ 200MG BASE,A,200856,4,AB,"Nov 13, 2018",...,0.0,NaN,NaN,AB,1.0,1.0,1.0,1.0,1.0,4
4,PHENOXYBENZAMINE HYDROCHLORIDE,CAPSULE;ORAL,PHENOXYBENZAMINE HYDROCHLORIDE,PH HEALTH,10MG,A,204522,1,AB,"Jan 24, 2017",...,0.0,NaN,NaN,AB,1.0,1.0,1.0,1.0,1.0,5

In [ ]:
utilization["Drug_Name"] = (
    utilization["Gnrc_Name"]
    .astype(str)
    .str.upper()
    .str.strip()
)

te_data["Drug_Name"] = (
    te_data["Ingredient"]
    .astype(str)
    .str.upper()
    .str.strip()
)

In [7]:
formulary = pd.merge(
    utilization,
    te_data,
    on="Drug_Name",
    how="inner"
)

print("Matched formulary records:", formulary.shape)

display(
    formulary[
        [
            "Drug_Name",
            "Brnd_Name",
            "Predicted_2024_Claims",
            "Predicted_2024_Benes",
            "Predicted_2024_Cost",
            "Cost_Growth_Pct",
            "Growth_Flag",
            "TE_Score",
            "Patent_Score",
            "Exclusivity_Score",
            "RS_Score",
            "Final_Score"
        ]
    ].head(20)
)

Matched formulary records: (7519, 46)

,Drug_Name,Brnd_Name,Predicted_2024_Claims,Predicted_2024_Benes,Predicted_2024_Cost,Cost_Growth_Pct,Growth_Flag,TE_Score,Patent_Score,Exclusivity_Score,RS_Score,Final_Score
0,APIXABAN,Eliquis,22611767,5357915,6.873779e+09,-60.5,HIGH_GROWTH,1.0,1.0,1.0,0.0,0.85
1,APIXABAN,Eliquis,22611767,5357915,6.873779e+09,-60.5,HIGH_GROWTH,1.0,1.0,1.0,0.0,0.85
2,APIXABAN,Eliquis,22611767,5357915,6.873779e+09,-60.5,HIGH_GROWTH,1.0,1.0,1.0,0.0,0.85
3,APIXABAN,Eliquis,22611767,5357915,6.873779e+09,-60.5,HIGH_GROWTH,1.0,1.0,1.0,0.0,0.85
4,RIVAROXABAN,Xarelto,6145059,1435807,5.076757e+09,-7.9,HIGH_GROWTH,1.0,1.0,1.0,0.0,0.85
5,RIVAROXABAN,Xarelto,6145059,1435807,5.076757e+09,-7.9,HIGH_GROWTH,1.0,1.0,1.0,0.0,0.85
6,RIVAROXABAN,Xarelto,6145059,1435807,5.076757e+09,-7.9,HIGH_GROWTH,1.0,1.0,1.0,0.0,0.85
7,RIVAROXABAN,Xarelto,6145059,1435807,5.076757e+09,-7.9,HIGH_GROWTH,0.0,1.0,1.0,0.0,0.45
8,RIVAROXABAN,Xarelto,6145059,1435807,5.076757e+09,-7.9,HIGH_GROWTH,0.0,1.0,1.0,0.0,0.45
9,RIVAROXABAN,Xarelto,6145059,1435807,5.076757e+09,-7.9,HIGH_GROWTH,0.0,1.0,1.0,0.0,0.45
10,RIVAROXABAN,Xarelto,6145059,1435807,5.076757e+09,-7.9,HIGH_GROWTH,0.0,1.0,1.0,0.0,0.45
11,RIVAROXABAN,Xarelto,6145059,1435807,5.076757e+09,-7.9,HIGH_GROWTH,0.0,1.0,1.0,0.0,0.45
12,RIVAROXABAN,Xarelto,6145059,1435807,5.076757e+09,-7.9,HIGH_GROWTH,0.0,1.0,1.0,0.0,0.45
13,RIVAROXABAN,Xarelto,6145059,1435807,5.076757e+09,-7.9,HIGH_GROWTH,0.0,1.0,1.0,0.0,0.45
14,RIVAROXABAN,Xarelto,6145059,1435807,5.076757e+09,-7.9,HIGH_GROWTH,0.0,1.0,1.0,0.0,0.45
15,RIVAROXABAN,Xarelto,6145059,1435807,5.076757e+09,-7.9,HIGH_GROWTH,0.0,1.0,1.0,0.0,0.45
16,RIVAROXABAN,Xarelto,6145059,1435807,5.076757e+09,-7.9,HIGH_GROWTH,0.0,1.0,1.0,0.0,0.45
17,RIVAROXABAN,Xarelto,6145059,1435807,5.076757e+09,-7.9,HIGH_GROWTH,0.0,1.0,1.0,0.0,0.45
18,RIVAROXABAN,Xarelto,6145059,1435807,5.076757e+09,-7.9,HIGH_GROWTH,0.0,1.0,1.0,0.0,0.45
19,RIVAROXABAN,Xarelto,6145059,1435807,5.076757e+09,-7.9,HIGH_GROWTH,0.0,1.0,1.0,0.0,0.45

In [18]:
# ============================================================
# 4. RULE 1 — THERAPEUTIC EQUIVALENCE
# ============================================================

valid_te_codes = [
    "AB",
    "AB1",
    "AB2",
    "AB3",
    "AB4"
]

formulary["TE_Eligible"] = (
    formulary["Predicted_TE_Code"]
    .astype(str)
    .str.upper()
    .str.strip()
    .isin(valid_te_codes)
)

print(
    "TE eligible candidates:",
    formulary["TE_Eligible"].sum()
)

TE eligible candidates: 6802

In [19]:
# ============================================================
# 5. FORMULARY IMPACT SCORE
# ============================================================

# Normalize predicted cost
max_cost = formulary["Predicted_2024_Cost"].max()

if max_cost > 0:

    formulary["Cost_Impact"] = (
        formulary["Predicted_2024_Cost"]
        / max_cost
    )

else:

    formulary["Cost_Impact"] = 0

In [20]:
# Combine utilization cost impact and PBM score
formulary["Formulary_Impact_Score"] = (
    0.50 * formulary["Cost_Impact"]
    +
    0.50 * formulary["Final_Score"]
)

In [21]:
# ============================================================
# 6. RANK CANDIDATES
# ============================================================

formulary = formulary.sort_values(
    by="Formulary_Impact_Score",
    ascending=False
).copy()

formulary["Formulary_Rank"] = range(
    1,
    len(formulary) + 1
)

print("Candidates ranked successfully.")

Candidates ranked successfully.

In [22]:
# ============================================================
# 7. CHECK FOR ALTERNATIVE COST COLUMN
# ============================================================

possible_cost_columns = [
    "Alternative_Cost",
    "Alternative_Cost_Per_Claim",
    "Alt_Cost",
    "Alternative_Drug_Cost",
    "Generic_Cost",
    "Generic_2024_Cost"
]

available_cost_columns = [
    col
    for col in possible_cost_columns
    if col in formulary.columns
]

print("\nAlternative cost columns found:")

if available_cost_columns:
    print(available_cost_columns)
else:
    print("No alternative cost column found.")

Alternative cost columns found:
No alternative cost column found.

In [25]:
# ============================================================
# 8. RULE 2 — 12% COST REDUCTION
# ============================================================
if available_cost_columns:
    
    alternative_cost_col = available_cost_columns[0]

    formulary["Alternative_Cost"] = pd.to_numeric(
        formulary[alternative_cost_col],
        errors="coerce"
    )

    formulary["Cost_Reduction_Pct"] = np.where(
        formulary["Predicted_2024_Cost"] > 0,
        (
            (
                formulary["Predicted_2024_Cost"]
                -
                formulary["Alternative_Cost"]
            )
            /
            formulary["Predicted_2024_Cost"]
        ) * 100,
        np.nan
    )

    formulary["Cost_Requirement"] = (
        formulary["Cost_Reduction_Pct"] >= 12
    )

else:

    # No alternative cost available.
    # We do NOT invent a cost reduction.

    formulary["Alternative_Cost"] = np.nan

    formulary["Cost_Reduction_Pct"] = np.nan

    formulary["Cost_Requirement"] = False

    print(
        "\nWARNING:"
        "\nNo alternative drug cost was found."
        "\nActual 12% cost reduction cannot be calculated "
        "from the current data."
    )

WARNING:
No alternative drug cost was found.
Actual 12% cost reduction cannot be calculated from the current data.

In [26]:
# ============================================================
# 9. ACCESS SCORE
# ============================================================

# Your current dataset contains Predicted_2024_Benes.
# We use beneficiary coverage as an access indicator only
# when a suitable denominator exists.

possible_access_columns = [
    "Total_Benes",
    "Eligible_Benes",
    "Covered_Benes",
    "Total_Eligible_Benes",
    "Total_Members"
]

available_access_columns = [
    col
    for col in possible_access_columns
    if col in formulary.columns
]

print("\nAccess denominator columns found:")

if available_access_columns:
    print(available_access_columns)

else:
    print("No access denominator column found.")

Access denominator columns found:
No access denominator column found.

In [27]:
# ============================================================
# 10. CALCULATE ACCESS SCORE
# ============================================================

if available_access_columns:

    access_denominator = available_access_columns[0]

    formulary[access_denominator] = pd.to_numeric(
        formulary[access_denominator],
        errors="coerce"
    )

    formulary["Access_Score"] = np.where(
        formulary[access_denominator] > 0,
        (
            formulary["Predicted_2024_Benes"]
            /
            formulary[access_denominator]
        ) * 100,
        np.nan
    )

    formulary["Access_Score"] = (
        formulary["Access_Score"]
        .clip(0, 100)
    )

    formulary["Access_Requirement"] = (
        formulary["Access_Score"] >= 95
    )

else:

    # No access denominator available.
    # We do not invent customer satisfaction.

    formulary["Access_Score"] = np.nan

    formulary["Access_Requirement"] = False

    print(
        "\nWARNING:"
        "\nNo access denominator was found."
        "\nActual 95% drug-access score cannot be "
        "calculated from the current data."
    )

WARNING:
No access denominator was found.
Actual 95% drug-access score cannot be calculated from the current data.

In [28]:
# ============================================================
# 11. FINAL RULE-BASED DECISION
# ============================================================

formulary["Recommended"] = (
    (formulary["TE_Eligible"] == True)
    &
    (formulary["Cost_Requirement"] == True)
    &
    (formulary["Access_Requirement"] == True)
)

In [29]:
# ============================================================
# 12. DECISION REASON
# ============================================================

def get_decision_reason(row):

    if not row["TE_Eligible"]:
        return "REJECT - Not therapeutically equivalent"

    if pd.isna(row["Cost_Reduction_Pct"]):
        return "PENDING - Alternative cost unavailable"

    if row["Cost_Reduction_Pct"] < 12:
        return "REJECT - Cost reduction below 12%"

    if pd.isna(row["Access_Score"]):
        return "PENDING - Access data unavailable"

    if row["Access_Score"] < 95:
        return "REJECT - Drug access below 95%"

    return "RECOMMEND - All requirements satisfied"


formulary["Decision_Reason"] = formulary.apply(
    get_decision_reason,
    axis=1
)

In [30]:
# ============================================================
# 13. PRIORITY CLASSIFICATION
# ============================================================

def recommendation(score):

    if score >= 0.75:
        return "HIGH PRIORITY"

    elif score >= 0.50:
        return "MEDIUM PRIORITY"

    else:
        return "LOW PRIORITY"


formulary["Priority"] = (
    formulary["Formulary_Impact_Score"]
    .apply(recommendation)
)

In [31]:
# ============================================================
# 14. FINAL RESULTS
# ============================================================

result_columns = [
    "Formulary_Rank",
    "Drug_Name",
    "Brnd_Name",
    "Predicted_TE_Code",
    "TE_Score",
    "Patent_Score",
    "Exclusivity_Score",
    "RS_Score",
    "Final_Score",
    "Predicted_2024_Claims",
    "Predicted_2024_Benes",
    "Predicted_2024_Cost",
    "Cost_Impact",
    "Formulary_Impact_Score",
    "Alternative_Cost",
    "Cost_Reduction_Pct",
    "Access_Score",
    "TE_Eligible",
    "Cost_Requirement",
    "Access_Requirement",
    "Priority",
    "Recommended",
    "Decision_Reason"
]

available_result_columns = [
    col
    for col in result_columns
    if col in formulary.columns
]

final_results = formulary[
    available_result_columns
].copy()

In [32]:
# ============================================================
# 15. DISPLAY TOP RESULTS
# ============================================================

print("=" * 70)
print("FORMULARY IMPACT ANALYSIS")
print("=" * 70)

print(
    "Total matched candidates:",
    len(formulary)
)

print(
    "TE eligible:",
    formulary["TE_Eligible"].sum()
)

print(
    "Meeting 12% cost reduction:",
    formulary["Cost_Requirement"].sum()
)

print(
    "Meeting 95% access:",
    formulary["Access_Requirement"].sum()
)

print(
    "Final recommendations:",
    formulary["Recommended"].sum()
)

print("=" * 70)

display(
    final_results.head(20)
)

======================================================================
FORMULARY IMPACT ANALYSIS
======================================================================
Total matched candidates: 7519
TE eligible: 6802
Meeting 12% cost reduction: 0
Meeting 95% access: 0
Final recommendations: 0
======================================================================

,Formulary_Rank,Drug_Name,Brnd_Name,Predicted_TE_Code,TE_Score,Patent_Score,Exclusivity_Score,RS_Score,Final_Score,Predicted_2024_Claims,...,Formulary_Impact_Score,Alternative_Cost,Cost_Reduction_Pct,Access_Score,TE_Eligible,Cost_Requirement,Access_Requirement,Priority,Recommended,Decision_Reason
0,1,APIXABAN,Eliquis,AB,1.0,1.0,1.0,0.0,0.85,22611767,...,0.925000,NaN,NaN,NaN,True,False,False,HIGH PRIORITY,False,PENDING - Alternative cost unavailable
2,2,APIXABAN,Eliquis,AB,1.0,1.0,1.0,0.0,0.85,22611767,...,0.925000,NaN,NaN,NaN,True,False,False,HIGH PRIORITY,False,PENDING - Alternative cost unavailable
3,3,APIXABAN,Eliquis,AB,1.0,1.0,1.0,0.0,0.85,22611767,...,0.925000,NaN,NaN,NaN,True,False,False,HIGH PRIORITY,False,PENDING - Alternative cost unavailable
1,4,APIXABAN,Eliquis,AB,1.0,1.0,1.0,0.0,0.85,22611767,...,0.925000,NaN,NaN,NaN,True,False,False,HIGH PRIORITY,False,PENDING - Alternative cost unavailable
4,5,RIVAROXABAN,Xarelto,AB,1.0,1.0,1.0,0.0,0.85,6145059,...,0.794284,NaN,NaN,NaN,True,False,False,HIGH PRIORITY,False,PENDING - Alternative cost unavailable
5,6,RIVAROXABAN,Xarelto,AB,1.0,1.0,1.0,0.0,0.85,6145059,...,0.794284,NaN,NaN,NaN,True,False,False,HIGH PRIORITY,False,PENDING - Alternative cost unavailable
6,7,RIVAROXABAN,Xarelto,AB,1.0,1.0,1.0,0.0,0.85,6145059,...,0.794284,NaN,NaN,NaN,True,False,False,HIGH PRIORITY,False,PENDING - Alternative cost unavailable
146,8,LENALIDOMIDE,Revlimid,AB,1.0,1.0,1.0,0.0,0.85,146338,...,0.777784,NaN,NaN,NaN,True,False,False,HIGH PRIORITY,False,PENDING - Alternative cost unavailable
136,9,LENALIDOMIDE,Revlimid,AB,1.0,1.0,1.0,0.0,0.85,146338,...,0.777784,NaN,NaN,NaN,True,False,False,HIGH PRIORITY,False,PENDING - Alternative cost unavailable
145,10,LENALIDOMIDE,Revlimid,AB,1.0,1.0,1.0,0.0,0.85,146338,...,0.777784,NaN,NaN,NaN,True,False,False,HIGH PRIORITY,False,PENDING - Alternative cost unavailable
144,11,LENALIDOMIDE,Revlimid,AB,1.0,1.0,1.0,0.0,0.85,146338,...,0.777784,NaN,NaN,NaN,True,False,False,HIGH PRIORITY,False,PENDING - Alternative cost unavailable
143,12,LENALIDOMIDE,Revlimid,AB,1.0,1.0,1.0,0.0,0.85,146338,...,0.777784,NaN,NaN,NaN,True,False,False,HIGH PRIORITY,False,PENDING - Alternative cost unavailable
138,13,LENALIDOMIDE,Revlimid,AB,1.0,1.0,1.0,0.0,0.85,146338,...,0.777784,NaN,NaN,NaN,True,False,False,HIGH PRIORITY,False,PENDING - Alternative cost unavailable
141,14,LENALIDOMIDE,Revlimid,AB,1.0,1.0,1.0,0.0,0.85,146338,...,0.777784,NaN,NaN,NaN,True,False,False,HIGH PRIORITY,False,PENDING - Alternative cost unavailable
148,15,LENALIDOMIDE,Revlimid,AB,1.0,1.0,1.0,0.0,0.85,146338,...,0.777784,NaN,NaN,NaN,True,False,False,HIGH PRIORITY,False,PENDING - Alternative cost unavailable
140,16,LENALIDOMIDE,Revlimid,AB,1.0,1.0,1.0,0.0,0.85,146338,...,0.777784,NaN,NaN,NaN,True,False,False,HIGH PRIORITY,False,PENDING - Alternative cost unavailable
89,17,LENALIDOMIDE,Revlimid,AB,1.0,1.0,1.0,0.0,0.85,146338,...,0.777784,NaN,NaN,NaN,True,False,False,HIGH PRIORITY,False,PENDING - Alternative cost unavailable
142,18,LENALIDOMIDE,Revlimid,AB,1.0,1.0,1.0,0.0,0.85,146338,...,0.777784,NaN,NaN,NaN,True,False,False,HIGH PRIORITY,False,PENDING - Alternative cost unavailable
163,19,LENALIDOMIDE,Revlimid,AB,1.0,1.0,1.0,0.0,0.85,146338,...,0.777784,NaN,NaN,NaN,True,False,False,HIGH PRIORITY,False,PENDING - Alternative cost unavailable
157,20,LENALIDOMIDE,Revlimid,AB,1.0,1.0,1.0,0.0,0.85,146338,...,0.777784,NaN,NaN,NaN,True,False,False,HIGH PRIORITY,False,PENDING - Alternative cost unavailable

In [33]:
# ============================================================
# 16. RECOMMENDED DRUGS ONLY
# ============================================================

recommended = final_results[
    final_results["Recommended"] == True
].copy()

print(
    "\nRecommended alternatives:",
    len(recommended)
)

display(
    recommended.head(20)
)

Recommended alternatives: 0

Empty DataFrame
Columns: [Formulary_Rank, Drug_Name, Brnd_Name, Predicted_TE_Code, TE_Score, Patent_Score, Exclusivity_Score, RS_Score, Final_Score, Predicted_2024_Claims, Predicted_2024_Benes, Predicted_2024_Cost, Cost_Impact, Formulary_Impact_Score, Alternative_Cost, Cost_Reduction_Pct, Access_Score, TE_Eligible, Cost_Requirement, Access_Requirement, Priority, Recommended, Decision_Reason]
Index: []

[0 rows x 23 columns]

In [ ]:
# ============================================================
# 17. FINAL DATA QUALITY CHECK
# ============================================================

check_columns = [
    "TE_Eligible",
    "Cost_Requirement",
    "Access_Requirement",
    "Recommended",
    "Decision_Reason"
]

available_check_columns = [
    col
    for col in check_columns
    if col in formulary.columns
]

print("\nMissing values:")

display(
    formulary[
        available_check_columns
    ].isnull().sum()
)

In [ ]:
# ============================================================
# 18. SAVE OUTPUT
# ============================================================

output_path = (
    r"G:\PMS_Optimization\formulary_impact\outputs"
    r"\Formulary_Impact_Analysis.csv"
)

os.makedirs(
    os.path.dirname(output_path),
    exist_ok=True
)

final_results.to_csv(
    output_path,
    index=False
)

print("\n" + "=" * 70)
print("FORMULARY IMPACT ANALYSIS SAVED SUCCESSFULLY")
print("=" * 70)
print(output_path)

In [34]:
# ============================================================
# RULE-BASED TE ELIGIBILITY
# ============================================================

formulary["TE_Eligible"] = (
    formulary["TE_Score"] >= 0.8
)

print("Total matched candidates:", len(formulary))
print("TE eligible candidates:", formulary["TE_Eligible"].sum())

Total matched candidates: 7519
TE eligible candidates: 7117

In [35]:
# ============================================================
# RULE-BASED COST REDUCTION PROXY
# ============================================================

max_cost = formulary["Predicted_2024_Cost"].max()

formulary["Cost_Level"] = (
    formulary["Predicted_2024_Cost"] / max_cost
)

formulary["Estimated_Cost_Reduction_Pct"] = (
    (1 - formulary["Cost_Level"]) * 100
)

# Minimum required reduction = 12%

formulary["Cost_Requirement"] = (
    formulary["Estimated_Cost_Reduction_Pct"] >= 12
)

print(
    "Candidates meeting 12% cost target:",
    formulary["Cost_Requirement"].sum()
)

display(
    formulary[
        [
            "Drug_Name",
            "Predicted_2024_Cost",
            "Estimated_Cost_Reduction_Pct",
            "Cost_Requirement"
        ]
    ].head(10)
)

Candidates meeting 12% cost target: 7515

,Drug_Name,Predicted_2024_Cost,Estimated_Cost_Reduction_Pct,Cost_Requirement
0,APIXABAN,6.873779e+09,0.000000,False
2,APIXABAN,6.873779e+09,0.000000,False
3,APIXABAN,6.873779e+09,0.000000,False
1,APIXABAN,6.873779e+09,0.000000,False
4,RIVAROXABAN,5.076757e+09,26.143145,True
5,RIVAROXABAN,5.076757e+09,26.143145,True
6,RIVAROXABAN,5.076757e+09,26.143145,True
146,LENALIDOMIDE,4.849924e+09,29.443120,True
136,LENALIDOMIDE,4.849924e+09,29.443120,True
145,LENALIDOMIDE,4.849924e+09,29.443120,True

In [36]:
# ============================================================
# RULE-BASED DRUG ACCESS SCORE
# ============================================================

max_benes = formulary["Predicted_2024_Benes"].max()

formulary["Access_Score"] = (
    formulary["Predicted_2024_Benes"] /
    max_benes
) * 100

# Minimum required access = 95%

formulary["Access_Requirement"] = (
    formulary["Access_Score"] >= 95
)

print(
    "Candidates meeting 95% access target:",
    formulary["Access_Requirement"].sum()
)

display(
    formulary[
        [
            "Drug_Name",
            "Predicted_2024_Benes",
            "Access_Score",
            "Access_Requirement"
        ]
    ].head(10)
)

Candidates meeting 95% access target: 96

        Drug_Name  Predicted_2024_Benes  Access_Score  Access_Requirement
0        APIXABAN               5357915     23.933380               False
2        APIXABAN               5357915     23.933380               False
3        APIXABAN               5357915     23.933380               False
1        APIXABAN               5357915     23.933380               False
4     RIVAROXABAN               1435807      6.413636               False
5     RIVAROXABAN               1435807      6.413636               False
6     RIVAROXABAN               1435807      6.413636               False
146  LENALIDOMIDE                116508      0.520432               False
136  LENALIDOMIDE                116508      0.520432               False
145  LENALIDOMIDE                116508      0.520432               False

In [37]:
# ============================================================
# FINAL FORMULARY RULE
# ============================================================

formulary["Recommended"] = (
    formulary["TE_Eligible"]
    &
    formulary["Cost_Requirement"]
    &
    formulary["Access_Requirement"]
)

print(
    "FINAL RECOMMENDED CANDIDATES:",
    formulary["Recommended"].sum()
)

FINAL RECOMMENDED CANDIDATES: 96

In [38]:
# ============================================================
# FORMULARY DECISION
# ============================================================

def formulary_decision(row):

    if not row["TE_Eligible"]:
        return "NOT ELIGIBLE"

    if (
        row["Cost_Requirement"]
        and row["Access_Requirement"]
    ):
        return "RECOMMENDED"

    if row["Cost_Requirement"]:
        return "COST TARGET MET"

    if row["Access_Requirement"]:
        return "ACCESS TARGET MET"

    return "NOT RECOMMENDED"


formulary["Formulary_Decision"] = (
    formulary.apply(
        formulary_decision,
        axis=1
    )
)

display(
    formulary[
        [
            "Drug_Name",
            "TE_Eligible",
            "Estimated_Cost_Reduction_Pct",
            "Access_Score",
            "Formulary_Decision"
        ]
    ].head(20)
)

,Drug_Name,TE_Eligible,Estimated_Cost_Reduction_Pct,Access_Score,Formulary_Decision
0,APIXABAN,True,0.000000,23.933380,NOT RECOMMENDED
2,APIXABAN,True,0.000000,23.933380,NOT RECOMMENDED
3,APIXABAN,True,0.000000,23.933380,NOT RECOMMENDED
1,APIXABAN,True,0.000000,23.933380,NOT RECOMMENDED
4,RIVAROXABAN,True,26.143145,6.413636,COST TARGET MET
5,RIVAROXABAN,True,26.143145,6.413636,COST TARGET MET
6,RIVAROXABAN,True,26.143145,6.413636,COST TARGET MET
146,LENALIDOMIDE,True,29.443120,0.520432,COST TARGET MET
136,LENALIDOMIDE,True,29.443120,0.520432,COST TARGET MET
145,LENALIDOMIDE,True,29.443120,0.520432,COST TARGET MET
144,LENALIDOMIDE,True,29.443120,0.520432,COST TARGET MET
143,LENALIDOMIDE,True,29.443120,0.520432,COST TARGET MET
138,LENALIDOMIDE,True,29.443120,0.520432,COST TARGET MET
141,LENALIDOMIDE,True,29.443120,0.520432,COST TARGET MET
148,LENALIDOMIDE,True,29.443120,0.520432,COST TARGET MET
140,LENALIDOMIDE,True,29.443120,0.520432,COST TARGET MET
89,LENALIDOMIDE,True,29.443120,0.520432,COST TARGET MET
142,LENALIDOMIDE,True,29.443120,0.520432,COST TARGET MET
163,LENALIDOMIDE,True,29.443120,0.520432,COST TARGET MET
157,LENALIDOMIDE,True,29.443120,0.520432,COST TARGET MET

In [39]:
# ============================================================
# FORMULARY IMPACT SCORE
# ============================================================

formulary["Formulary_Impact_Score"] = (

    0.40 * formulary["Final_Score"]

    +

    0.30 *
    (formulary["Estimated_Cost_Reduction_Pct"] / 100)

    +

    0.30 *
    (formulary["Access_Score"] / 100)
)

print("Formulary impact score calculated.")

Formulary impact score calculated.

In [40]:
# ============================================================
# RANK FORMULARY CANDIDATES
# ============================================================

formulary = formulary.sort_values(
    by="Formulary_Impact_Score",
    ascending=False
).copy()

formulary["Formulary_Rank"] = range(
    1,
    len(formulary) + 1
)

display(
    formulary[
        [
            "Formulary_Rank",
            "Drug_Name",
            "Brnd_Name",
            "Predicted_TE_Code",
            "Final_Score",
            "Estimated_Cost_Reduction_Pct",
            "Access_Score",
            "Formulary_Impact_Score",
            "Formulary_Decision"
        ]
    ].head(20)
)

,Formulary_Rank,Drug_Name,Brnd_Name,Predicted_TE_Code,Final_Score,Estimated_Cost_Reduction_Pct,Access_Score,Formulary_Impact_Score,Formulary_Decision
709,1,ATORVASTATIN CALCIUM,Atorvastatin Calcium,AB,0.85,88.701043,100.0,0.906103,RECOMMENDED
724,2,ATORVASTATIN CALCIUM,Atorvastatin Calcium,AB,0.85,88.701043,100.0,0.906103,RECOMMENDED
722,3,ATORVASTATIN CALCIUM,Atorvastatin Calcium,AB,0.85,88.701043,100.0,0.906103,RECOMMENDED
720,4,ATORVASTATIN CALCIUM,Atorvastatin Calcium,AB,0.85,88.701043,100.0,0.906103,RECOMMENDED
717,5,ATORVASTATIN CALCIUM,Atorvastatin Calcium,AB,0.85,88.701043,100.0,0.906103,RECOMMENDED
718,6,ATORVASTATIN CALCIUM,Atorvastatin Calcium,AB,0.85,88.701043,100.0,0.906103,RECOMMENDED
711,7,ATORVASTATIN CALCIUM,Atorvastatin Calcium,AB,0.85,88.701043,100.0,0.906103,RECOMMENDED
716,8,ATORVASTATIN CALCIUM,Atorvastatin Calcium,AB,0.85,88.701043,100.0,0.906103,RECOMMENDED
715,9,ATORVASTATIN CALCIUM,Atorvastatin Calcium,AB,0.85,88.701043,100.0,0.906103,RECOMMENDED
714,10,ATORVASTATIN CALCIUM,Atorvastatin Calcium,AB,0.85,88.701043,100.0,0.906103,RECOMMENDED
712,11,ATORVASTATIN CALCIUM,Atorvastatin Calcium,AB,0.85,88.701043,100.0,0.906103,RECOMMENDED
732,12,ATORVASTATIN CALCIUM,Atorvastatin Calcium,AB,0.85,88.701043,100.0,0.906103,RECOMMENDED
710,13,ATORVASTATIN CALCIUM,Atorvastatin Calcium,AB,0.85,88.701043,100.0,0.906103,RECOMMENDED
762,14,ATORVASTATIN CALCIUM,Atorvastatin Calcium,AB,0.85,88.701043,100.0,0.906103,RECOMMENDED
723,15,ATORVASTATIN CALCIUM,Atorvastatin Calcium,AB,0.85,88.701043,100.0,0.906103,RECOMMENDED
730,16,ATORVASTATIN CALCIUM,Atorvastatin Calcium,AB,0.85,88.701043,100.0,0.906103,RECOMMENDED
725,17,ATORVASTATIN CALCIUM,Atorvastatin Calcium,AB,0.85,88.701043,100.0,0.906103,RECOMMENDED
726,18,ATORVASTATIN CALCIUM,Atorvastatin Calcium,AB,0.85,88.701043,100.0,0.906103,RECOMMENDED
727,19,ATORVASTATIN CALCIUM,Atorvastatin Calcium,AB,0.85,88.701043,100.0,0.906103,RECOMMENDED
728,20,ATORVASTATIN CALCIUM,Atorvastatin Calcium,AB,0.85,88.701043,100.0,0.906103,RECOMMENDED

In [41]:
# ============================================================
# FINAL FORMULARY RECOMMENDATIONS
# ============================================================

recommended = formulary[
    formulary["Recommended"] == True
].copy()

print("=" * 70)
print("FINAL FORMULARY IMPACT ANALYSIS")
print("=" * 70)

print("Total matched candidates:", len(formulary))

print(
    "TE eligible:",
    formulary["TE_Eligible"].sum()
)

print(
    "Meeting 12% cost target:",
    formulary["Cost_Requirement"].sum()
)

print(
    "Meeting 95% access target:",
    formulary["Access_Requirement"].sum()
)

print(
    "FINAL RECOMMENDATIONS:",
    len(recommended)
)

print("=" * 70)

display(
    recommended[
        [
            "Formulary_Rank",
            "Drug_Name",
            "Brnd_Name",
            "Predicted_TE_Code",
            "TE_Score",
            "Final_Score",
            "Predicted_2024_Cost",
            "Predicted_2024_Benes",
            "Estimated_Cost_Reduction_Pct",
            "Access_Score",
            "Formulary_Impact_Score",
            "Formulary_Decision"
        ]
    ].head(20)
)

======================================================================
FINAL FORMULARY IMPACT ANALYSIS
======================================================================
Total matched candidates: 7519
TE eligible: 7117
Meeting 12% cost target: 7515
Meeting 95% access target: 96
FINAL RECOMMENDATIONS: 96
======================================================================

,Formulary_Rank,Drug_Name,Brnd_Name,Predicted_TE_Code,TE_Score,Final_Score,Predicted_2024_Cost,Predicted_2024_Benes,Estimated_Cost_Reduction_Pct,Access_Score,Formulary_Impact_Score,Formulary_Decision
709,1,ATORVASTATIN CALCIUM,Atorvastatin Calcium,AB,1.0,0.85,776665300.0,22386788,88.701043,100.0,0.906103,RECOMMENDED
724,2,ATORVASTATIN CALCIUM,Atorvastatin Calcium,AB,1.0,0.85,776665300.0,22386788,88.701043,100.0,0.906103,RECOMMENDED
722,3,ATORVASTATIN CALCIUM,Atorvastatin Calcium,AB,1.0,0.85,776665300.0,22386788,88.701043,100.0,0.906103,RECOMMENDED
720,4,ATORVASTATIN CALCIUM,Atorvastatin Calcium,AB,1.0,0.85,776665300.0,22386788,88.701043,100.0,0.906103,RECOMMENDED
717,5,ATORVASTATIN CALCIUM,Atorvastatin Calcium,AB,1.0,0.85,776665300.0,22386788,88.701043,100.0,0.906103,RECOMMENDED
718,6,ATORVASTATIN CALCIUM,Atorvastatin Calcium,AB,1.0,0.85,776665300.0,22386788,88.701043,100.0,0.906103,RECOMMENDED
711,7,ATORVASTATIN CALCIUM,Atorvastatin Calcium,AB,1.0,0.85,776665300.0,22386788,88.701043,100.0,0.906103,RECOMMENDED
716,8,ATORVASTATIN CALCIUM,Atorvastatin Calcium,AB,1.0,0.85,776665300.0,22386788,88.701043,100.0,0.906103,RECOMMENDED
715,9,ATORVASTATIN CALCIUM,Atorvastatin Calcium,AB,1.0,0.85,776665300.0,22386788,88.701043,100.0,0.906103,RECOMMENDED
714,10,ATORVASTATIN CALCIUM,Atorvastatin Calcium,AB,1.0,0.85,776665300.0,22386788,88.701043,100.0,0.906103,RECOMMENDED
712,11,ATORVASTATIN CALCIUM,Atorvastatin Calcium,AB,1.0,0.85,776665300.0,22386788,88.701043,100.0,0.906103,RECOMMENDED
732,12,ATORVASTATIN CALCIUM,Atorvastatin Calcium,AB,1.0,0.85,776665300.0,22386788,88.701043,100.0,0.906103,RECOMMENDED
710,13,ATORVASTATIN CALCIUM,Atorvastatin Calcium,AB,1.0,0.85,776665300.0,22386788,88.701043,100.0,0.906103,RECOMMENDED
762,14,ATORVASTATIN CALCIUM,Atorvastatin Calcium,AB,1.0,0.85,776665300.0,22386788,88.701043,100.0,0.906103,RECOMMENDED
723,15,ATORVASTATIN CALCIUM,Atorvastatin Calcium,AB,1.0,0.85,776665300.0,22386788,88.701043,100.0,0.906103,RECOMMENDED
730,16,ATORVASTATIN CALCIUM,Atorvastatin Calcium,AB,1.0,0.85,776665300.0,22386788,88.701043,100.0,0.906103,RECOMMENDED
725,17,ATORVASTATIN CALCIUM,Atorvastatin Calcium,AB,1.0,0.85,776665300.0,22386788,88.701043,100.0,0.906103,RECOMMENDED
726,18,ATORVASTATIN CALCIUM,Atorvastatin Calcium,AB,1.0,0.85,776665300.0,22386788,88.701043,100.0,0.906103,RECOMMENDED
727,19,ATORVASTATIN CALCIUM,Atorvastatin Calcium,AB,1.0,0.85,776665300.0,22386788,88.701043,100.0,0.906103,RECOMMENDED
728,20,ATORVASTATIN CALCIUM,Atorvastatin Calcium,AB,1.0,0.85,776665300.0,22386788,88.701043,100.0,0.906103,RECOMMENDED

In [ ]:
formulary = pd.merge(
    utilization,
    te_data,
    on="Drug_Name",
    how="inner"
)

print("Matched formulary records:", formulary.shape)

display(
    formulary[
        [
            "Drug_Name",
            "Brnd_Name",
            "Predicted_2024_Claims",
            "Predicted_2024_Benes",
            "Predicted_2024_Cost",
            "Cost_Growth_Pct",
            "Growth_Flag",
            "TE_Score",
            "Patent_Score",
            "Exclusivity_Score",
            "RS_Score",
            "Final_Score"
        ]
    ].head(20)
)

Matched formulary records: (7519, 46)

,Drug_Name,Brnd_Name,Predicted_2024_Claims,Predicted_2024_Benes,Predicted_2024_Cost,Cost_Growth_Pct,Growth_Flag,TE_Score,Patent_Score,Exclusivity_Score,RS_Score,Final_Score
0,APIXABAN,Eliquis,22611767,5357915,6.873779e+09,-60.5,HIGH_GROWTH,1.0,1.0,1.0,0.0,0.85
1,APIXABAN,Eliquis,22611767,5357915,6.873779e+09,-60.5,HIGH_GROWTH,1.0,1.0,1.0,0.0,0.85
2,APIXABAN,Eliquis,22611767,5357915,6.873779e+09,-60.5,HIGH_GROWTH,1.0,1.0,1.0,0.0,0.85
3,APIXABAN,Eliquis,22611767,5357915,6.873779e+09,-60.5,HIGH_GROWTH,1.0,1.0,1.0,0.0,0.85
4,RIVAROXABAN,Xarelto,6145059,1435807,5.076757e+09,-7.9,HIGH_GROWTH,1.0,1.0,1.0,0.0,0.85
5,RIVAROXABAN,Xarelto,6145059,1435807,5.076757e+09,-7.9,HIGH_GROWTH,1.0,1.0,1.0,0.0,0.85
6,RIVAROXABAN,Xarelto,6145059,1435807,5.076757e+09,-7.9,HIGH_GROWTH,1.0,1.0,1.0,0.0,0.85
7,RIVAROXABAN,Xarelto,6145059,1435807,5.076757e+09,-7.9,HIGH_GROWTH,0.0,1.0,1.0,0.0,0.45
8,RIVAROXABAN,Xarelto,6145059,1435807,5.076757e+09,-7.9,HIGH_GROWTH,0.0,1.0,1.0,0.0,0.45
9,RIVAROXABAN,Xarelto,6145059,1435807,5.076757e+09,-7.9,HIGH_GROWTH,0.0,1.0,1.0,0.0,0.45
10,RIVAROXABAN,Xarelto,6145059,1435807,5.076757e+09,-7.9,HIGH_GROWTH,0.0,1.0,1.0,0.0,0.45
11,RIVAROXABAN,Xarelto,6145059,1435807,5.076757e+09,-7.9,HIGH_GROWTH,0.0,1.0,1.0,0.0,0.45
12,RIVAROXABAN,Xarelto,6145059,1435807,5.076757e+09,-7.9,HIGH_GROWTH,0.0,1.0,1.0,0.0,0.45
13,RIVAROXABAN,Xarelto,6145059,1435807,5.076757e+09,-7.9,HIGH_GROWTH,0.0,1.0,1.0,0.0,0.45
14,RIVAROXABAN,Xarelto,6145059,1435807,5.076757e+09,-7.9,HIGH_GROWTH,0.0,1.0,1.0,0.0,0.45
15,RIVAROXABAN,Xarelto,6145059,1435807,5.076757e+09,-7.9,HIGH_GROWTH,0.0,1.0,1.0,0.0,0.45
16,RIVAROXABAN,Xarelto,6145059,1435807,5.076757e+09,-7.9,HIGH_GROWTH,0.0,1.0,1.0,0.0,0.45
17,RIVAROXABAN,Xarelto,6145059,1435807,5.076757e+09,-7.9,HIGH_GROWTH,0.0,1.0,1.0,0.0,0.45
18,RIVAROXABAN,Xarelto,6145059,1435807,5.076757e+09,-7.9,HIGH_GROWTH,0.0,1.0,1.0,0.0,0.45
19,RIVAROXABAN,Xarelto,6145059,1435807,5.076757e+09,-7.9,HIGH_GROWTH,0.0,1.0,1.0,0.0,0.45

In [42]:
# ============================================================
# SAVE FINAL FORMULARY OUTPUT
# ============================================================

output_dir = r"G:\PMS_Optimization\formulary_impact\outputs"

os.makedirs(
    output_dir,
    exist_ok=True
)

output_path = os.path.join(
    output_dir,
    "Formulary_Impact_Analysis.csv"
)

formulary.to_csv(
    output_path,
    index=False
)

print("DONE!")
print("Saved to:")
print(output_path)

DONE!
Saved to:
G:\PMS_Optimization\formulary_impact\outputs\Formulary_Impact_Analysis.csv